version: '3.7'

services:
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myapp
    ports:
      - 3306:3306
